set omnifunc=syntaxcomplete#Complete
set scrolloff=1
set scrolljump=5
set softtabstop=2
set shiftwidth=2
set shiftround
set expandtab
set smarttab
set number         
set nofoldenable  
scriptencoding utf-8
set cursorline          
set nowrap             
set ignorecase
set smartcase
syntax on   
set noswapfile
set hlsearch
set incsearch
"set timeoutlen=1000 ttimeoutlen=0
set timeout
set ttimeout
set timeoutlen=1000
set ttimeoutlen=0
"set cmdheight=5
